// Mock data for building the dashboard without a database (and for demos:
// when DATABASE_URL is unset the site runs on this). Every status appears.
import type { Submission } from "./types";

const now = Date.now();
const ago = (min: number) => new Date(now - min * 60_000).toISOString();

function sub(p: Partial<Submission> & Pick<Submission, "owner" | "forkNumber" | "status">): Submission {
  return {
    repo: "solari-cookbook",
    title: "solari-cookbook",
    description: "",
    repoUrl: `https://github.com/${p.owner}/${p.repo ?? "solari-cookbook"}`,
    commitSha: null,
    projectType: "cli",
    stack: [],
    productsUsed: [],
    demoProduct: null,
    bootMs: null,
    score: null,
    summary: null,
    thumbnailUrl: null,
    previewUrl: null,
    videoUrl: null,
    captionsUrl: null,
    errorTail: null,
    discoveredAt: ago(60 * 24),
    scannedAt: ago(12),
    hidden: false,
    ...p,
  };
}

const score = (boots: number, works: number, usesSolari: number, useCase: number, polish: number) => ({
  boots,
  works,
  usesSolari,
  useCase,
  polish,
  total: Math.round(((boots + works + usesSolari + useCase + polish) / 5) * 10) / 10,
});

export const MOCK_SUBMISSIONS: Submission[] = [
  sub({
    owner: "alice-chen",
    forkNumber: 17,
    status: "booted",
    title: "solari-price-watch",
    description:
      "Tracks competitor prices across 40 Shopify stores using parallel stealth browsers, then diffs each crawl into a daily report.",
    commitSha: "3f2a91c8d1e04b7a9c2f",
    projectType: "web",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "fastapi", name: "FastAPI" },
      { slug: "googlechrome", name: "Chrome" },
      { slug: "postgresql", name: "PostgreSQL" },
    ],
    productsUsed: ["browser", "sandbox"],
    demoProduct: "browser",
    bootMs: 39_800,
    score: score(5, 4, 4, 5, 3),
    thumbnailUrl: "/mock/price-watch.svg",
    discoveredAt: ago(60 * 30),
    scannedAt: ago(12),
  }),
  sub({
    owner: "devon-ray",
    forkNumber: 23,
    status: "booted",
    title: "desktop-qa-bot",
    description:
      "A computer-use agent that opens exported spreadsheets on a Solari Desktop and checks every total against the source data.",
    commitSha: "a91be07f55c3",
    projectType: "desktop_agent",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "anthropic", name: "Anthropic" },
      { slug: "ubuntu", name: "Ubuntu" },
    ],
    productsUsed: ["desktop", "sandbox"],
    demoProduct: "desktop",
    bootMs: 52_300,
    score: score(5, 5, 5, 4, 4),
    thumbnailUrl: "/mock/desktop-qa.svg",
    discoveredAt: ago(60 * 20),
    scannedAt: ago(9),
  }),
  sub({
    owner: "mkowalski",
    forkNumber: 31,
    status: "booted",
    title: "form-sentinel",
    description:
      "Submits every contact form on a site every 15 minutes and alerts when a lead fails to arrive in the CRM sandbox.",
    commitSha: "77c0d2e19ab4",
    projectType: "browser_agent",
    stack: [
      { slug: "typescript", name: "TypeScript" },
      { slug: "nodedotjs", name: "Node.js" },
      { slug: "googlechrome", name: "Chrome" },
    ],
    productsUsed: ["browser", "sandbox"],
    demoProduct: "browser",
    bootMs: 28_900,
    score: score(4, 4, 4, 3, 4),
    thumbnailUrl: "/mock/form-sentinel.svg",
    discoveredAt: ago(60 * 12),
    scannedAt: ago(15),
  }),
  sub({
    owner: "priya-n",
    forkNumber: 36,
    status: "running",
    title: "sandbox-grader",
    description:
      "Grades student Python homework by forking one warm sandbox snapshot per submission and running the test suite in parallel.",
    commitSha: "0be4410c2f9d",
    projectType: "cli",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "pytest", name: "pytest" },
      { slug: "docker", name: "Docker" },
    ],
    productsUsed: ["sandbox"],
    demoProduct: "sandbox",
    thumbnailUrl: "/mock/sandbox-grader.svg",
    discoveredAt: ago(60 * 6),
    scannedAt: ago(1),
  }),
  sub({
    owner: "tomasz-dev",
    forkNumber: 29,
    status: "build_failed",
    title: "invoice-extractor",
    description:
      "Logs into supplier portals, downloads invoices as PDFs and extracts line items into a CSV inside a sandbox.",
    commitSha: "c3d9e8812f00",
    projectType: "browser_agent",
    stack: [
      { slug: "nodedotjs", name: "Node.js" },
      { slug: "typescript", name: "TypeScript" },
      { slug: "googlechrome", name: "Chrome" },
    ],
    productsUsed: ["browser", "sandbox"],
    score: score(1, 1, 3, 4, 2),
    errorTail: [
      "npm ERR! code ERESOLVE",
      "npm ERR! ERESOLVE unable to resolve dependency tree",
      "npm ERR! peer typescript@\"^4.9\" from ts-node@10.9.1",
      "npm ERR! Found: typescript@5.6.3",
    ],
    discoveredAt: ago(60 * 14),
    scannedAt: ago(18),
  }),
  sub({
    owner: "lena-okafor",
    forkNumber: 33,
    status: "build_failed",
    title: "ghost-cart",
    description:
      "Abandoned-cart tester that walks a checkout flow with stealth mode and a residential proxy in five countries.",
    commitSha: "58aa01c7e3b2",
    projectType: "browser_agent",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "googlechrome", name: "Chrome" },
    ],
    productsUsed: ["browser"],
    score: score(1, 1, 3, 3, 2),
    errorTail: [
      "Traceback (most recent call last):",
      '  File "/work/ghost-cart/main.py", line 4, in <module>',
      "    from solari_browser import Solari",
      "ModuleNotFoundError: No module named 'solari_browser'",
    ],
    discoveredAt: ago(60 * 9),
    scannedAt: ago(21),
  }),
  sub({
    owner: "sam-whitfield",
    forkNumber: 27,
    status: "timeout",
    title: "crawl-lab",
    description: "A notebook-style crawler playground that streams a Solari Browser into a Jupyter kernel running in a sandbox.",
    commitSha: "9d1c40e2aa81",
    projectType: "web",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "jupyter", name: "Jupyter" },
      { slug: "googlechrome", name: "Chrome" },
    ],
    productsUsed: ["browser", "sandbox"],
    score: score(2, 1, 4, 3, 3),
    errorTail: [
      "$ jupyter lab --ip 0.0.0.0 --port 8888",
      "[I 14:02:11 ServerApp] Building JupyterLab assets (production, minimized)",
      "waiting for port 8888 ...",
      "timed out after 600s waiting for port 8888",
    ],
    discoveredAt: ago(60 * 16),
    scannedAt: ago(26),
  }),
  sub({
    owner: "noor-a",
    forkNumber: 34,
    status: "needs_secrets",
    title: "agent-desk",
    description: "Hands a Solari Desktop to a planning agent that files expense reports from receipts dropped in a folder.",
    commitSha: "e2f7a1b09c35",
    projectType: "desktop_agent",
    stack: [
      { slug: "python", name: "Python" },
      { slug: "ubuntu", name: "Ubuntu" },
    ],
    productsUsed: ["desktop"],
    score: score(1, 1, 4, 4, 3),
    errorTail: ["Missing required environment variables:", "  EXPENSIFY_API_TOKEN", "  RECEIPTS_BUCKET_URL"],
    discoveredAt: ago(60 * 7),
    scannedAt: ago(30),
  }),
  sub({
    owner: "jpark",
    forkNumber: 12,
    status: "skipped",
    title: "solari-cookbook",
    description: "No changes from upstream.",
    commitSha: "7a45864a0b17",
    discoveredAt: ago(60 * 40),
    scannedAt: ago(33),
  }),
  sub({
    owner: "rivera-labs",
    forkNumber: 38,
    status: "queued",
    title: "solari-cookbook",
    description: "Found in the last scan. Waiting for a sandbox.",
    discoveredAt: ago(3),
    scannedAt: null,
  }),
  sub({
    owner: "quiet-fox",
    forkNumber: 19,
    status: "opted_out",
    title: "private-project",
    description: "Hidden at the owner's request.",
    hidden: true,
  }),
];

export const MOCK_SCAN = { lastScanAt: ago(4), running: true };

/** Solari VMs (sandboxes, browsers and desktops) launched per submission, all runs. */
export const MOCK_VM_COUNTS: Record<string, number> = {
  "alice-chen": 14,
  "devon-ray": 9,
  mkowalski: 11,
  "priya-n": 26,
  "tomasz-dev": 3,
  "lena-okafor": 2,
  "sam-whitfield": 4,
  "noor-a": 1,
  jpark: 0,
};
